### ISSUE TITLE
version 7.7.2 on pypi not being found for linux

### ISSUE THREAD

**Issue by shimwell** [CadQuery/ocp-build-system#24]
Hi all

I've been trying to install cadquery-ocp 7.7.2 with pip on a regular ubuntu machine and not being able to install version 7.7.2 even though I can see 7.7.2 in the releases on [pypi](https://pypi.org/project/cadquery-ocp/7.7.2/#files) and on [this repo releases](https://github.com/CadQuery/ocp-build-system/releases/tag/7.7.2.0).

in a python 3.12 environment no versions are found
![Screenshot from 2024-03-13 22-12-53](https://github.com/CadQuery/ocp-build-system/assets/8583900/121676ba-8fd6-4db4-a79b-a9f02566170e)

in a python 3.11 environment 7.7.0 and 7.7.0a versions are found
![Screenshot from 2024-03-13 22-13-53](https://github.com/CadQuery/ocp-build-system/assets/8583900/f1de52f2-4953-4f97-b504-e435c754a5b7)

in a python 3.10 environment several older versions are found but not 7.7.2
![Screenshot from 2024-03-13 22-15-11](https://github.com/CadQuery/ocp-build-system/assets/8583900/966fb32d-c623-4d0e-ba3f-e4e01b146bfd)

I've also tried installing the wheels directly from the repo  releases and from pypi urls

pip install from repo release wheel url in python 3.12 env
![Screenshot from 2024-03-13 22-18-07](https://github.com/CadQuery/ocp-build-system/assets/8583900/8d4dc739-26b6-4975-8945-f0d92701b3ff)

pip install from pypi release wheel url in python 3.12 env
![Screenshot from 2024-03-13 22-19-42](https://github.com/CadQuery/ocp-build-system/assets/8583900/b8071d47-b556-44ca-b743-bb28ec332381)

I've also tried with the ```--pre``` comand for pip but no luck.

Am I doing something wrong or is the 7.7.2 release somehow different to the 7.7.0 release?

Many thanks

**Comment by jmwright** [comment]
@shimwell That laptop is not ARM based, is it? Also, make sure pip is updated:

```
pip install --upgrade pip
```

**Comment by shimwell** [comment]
Sorry I should have mentioned I'm on the newest pip version 24.0 and it is a normal x86 cpu (not arm).

**Comment by shimwell** [comment]
Ah it just worked in a docker image (Ubuntu:latest) so it must be something on my local setup

**Comment by shimwell** [comment]
I've not updated my OS to Ubuntu 22.04 and everything is installing nicely. I shall close this issue and I think it is safe to assume user error or local environment issues
